# Generated by Django 2.2.5 on 2019-11-11 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_serverity', models.CharField(choices=[('1', 'Minimal'), ('2', 'Mild'), ('3', 'Moderate'), ('4', 'Severe')], default='1', max_length=2)),
                ('injury_type', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_date', models.DateField()),
                ('injury_comments', models.CharField(max_length=255, null=True)),
                ('recovery_date', models.DateField()),
                ('conditioning_notes', models.CharField(max_length=225, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('injury', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.Injury')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
    ]
