# Generated by Django 2.2.5 on 2019-11-13 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0010_delete_playerskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_cert_no', models.IntegerField(default=0, verbose_name='Birth Certificate No')),
                ('birth_cert_pdf', models.FileField(blank=True, null=True, upload_to='files/certs', verbose_name='Birth Certificate PDF')),
                ('check_cert', models.BooleanField(default=False, verbose_name='Verify Cert')),
                ('passport', models.CharField(max_length=150, null=True, verbose_name='Passport No')),
                ('passport_image', models.FileField(blank=True, null=True, upload_to='files/passports', verbose_name='Passport PDF')),
                ('check_passport', models.BooleanField(default=False, verbose_name='Verify Passport')),
                ('id_number', models.CharField(max_length=9, null=True, verbose_name='ID No')),
                ('id_image', models.FileField(blank=True, null=True, upload_to='files/ids', verbose_name='ID PDF')),
                ('check_id', models.BooleanField(default=False, verbose_name='Verify Id')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
    ]
