# Generated by Django 2.2.5 on 2019-11-14 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verify',
            name='id',
        ),
        migrations.AlterField(
            model_name='verify',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='players.Player'),
        ),
    ]
