# Generated by Django 2.2.5 on 2019-11-12 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('players', '0002_auto_20191113_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Position'),
        ),
    ]
