# Generated by Django 2.2.5 on 2019-11-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_physicalcriteria_playerskill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhysicalCriteria',
        ),
    ]
