# Generated by Django 2.2.5 on 2019-11-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_delete_physicalcriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='injury_history',
            field=models.CharField(max_length=225, null=True, verbose_name='Injury History'),
        ),
    ]
