# Generated by Django 2.2.5 on 2019-11-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_auto_20191113_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerSkill',
        ),
    ]
