# Generated by Django 2.2.5 on 2019-11-13 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_delete_playerskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_step', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('swerve', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('change_pace', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('hand_off', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('skill_level', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('catch_pass', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('catch_high_ball', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('catch_low_ball', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('catch_good_pass', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('pass_left', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('pass_right', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('spin_pass_left', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('spin_pass_right', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('offload_right', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('offload_left', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('scissors_left', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('scissors_right', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('scrumhalf_pass_left', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('scrumhalf_pass_right', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('clean_out', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('carrying', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('ball_retention', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('reaction', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('decision_making', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('communication', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('running_lines', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('work_rate', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('second_touches', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('punt_left', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('punt_right', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('grubber_left', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('drop_kick_left', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('drop_kick_right', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('chip_left', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('chip_right', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('goal_kick_left', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('goal_kick_right', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('kickoffs', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('defence_workrate', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('attack_workrate', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('throwing', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('scrummaging_t', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('scrammaging_p', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('lineouts', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('self_drive', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('work_ethic', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('focus', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('coachable', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('slef_awareness', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('others_awareness', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('self_reliance', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('life_balance', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('team_person', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('ethos_and_values', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Joined')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
    ]
