# Generated by Django 2.2.5 on 2019-11-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_playerskill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerSkill',
        ),
    ]
