# Generated by Django 2.2.5 on 2019-11-11 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditioning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench', models.IntegerField()),
                ('squats', models.IntegerField()),
                ('v_jumps', models.DecimalField(decimal_places=2, max_digits=5)),
                ('h_jumps', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yoyo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('t_test_right', models.DecimalField(decimal_places=2, max_digits=5)),
                ('t_test_left', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bicep', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waist', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hip', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thigh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('m10', models.DecimalField(decimal_places=2, max_digits=5)),
                ('m40', models.DecimalField(decimal_places=2, max_digits=5)),
                ('m60', models.DecimalField(decimal_places=2, max_digits=5)),
                ('suppliment_taken', models.CharField(max_length=225, null=True)),
                ('conditioning_notes', models.CharField(max_length=225, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
    ]
