# Generated by Django 2.2.5 on 2019-11-13 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_delete_playerskill'),
        ('snc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catch_pass', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=15, verbose_name='Catch & Pass')),
                ('tackle', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=15, verbose_name='Tackles')),
                ('post_tackle', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=15, verbose_name='Post-tackle')),
                ('carry', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=15, verbose_name='Carry')),
                ('clean_out', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=15, verbose_name='Clean Out')),
                ('off_load', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=15, verbose_name='Off-load')),
                ('one_on_one', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=15, verbose_name='One on One')),
                ('support', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=15, verbose_name='Support Play')),
                ('high_ball', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=15, verbose_name='High Ball')),
                ('kicking', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], max_length=15, null=True, verbose_name='Kicking(Grubber/Punt/Chip)')),
                ('commment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
    ]
