# Generated by Django 2.2.5 on 2019-11-14 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_delete_playerskill'),
        ('snc', '0002_technicalskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacticleSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positioning', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=15, verbose_name='Positioning')),
                ('gameplan', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=15, verbose_name='Game Plan and Role Understanding')),
                ('workrate', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=15, verbose_name='Workrate')),
                ('tactical_awareness', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=15, verbose_name='Tactical awareness')),
                ('communication', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=15, verbose_name='Communication')),
                ('scrummaging', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=15, verbose_name='Scrummaging')),
                ('throwing', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=15, verbose_name='Throwing(Hooker)')),
                ('kicking_post', models.CharField(choices=[('1', 'Work On'), ('2', 'Adequate'), ('3', 'Excellent')], default='1', max_length=15, verbose_name='Kicking for Post')),
                ('tacticle_commment', models.TextField(verbose_name='Commments')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
    ]
