# Generated by Django 2.2.5 on 2019-11-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snc', '0004_leadershipskill_mentalskill_physicalskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalskill',
            name='body_weight',
            field=models.IntegerField(verbose_name='Body Weight'),
        ),
    ]
